services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ghcr.io/niflheimdevs/wtf-frontend
    container_name: frontend_app
    restart: always
    ports:
      - "3000:80"
    env_file:
      - ./.env
